spring.application.name=sispen-ms-admin-files
server.port=28085

jwt.auth.converter.principle-attribute=preferred_username
jwt.auth.converter.resource-id=sispen-client-api

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/dane-realm-dev

sispen.folder.url-base=/usr/local/dane/sispen/